server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: localhost
    username: admin
    password: 123456
    virtual-host: /host_admin

leyou:
  sms:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: 乐优商城
    verifyCodeTemplate: SMS_148614415
